# Production Docker Compose for api.climateriskplan.com
# This replaces all the other docker-compose variants

services:
  app:
    build: ..
    container_name: resilience-api
    restart: unless-stopped
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
      - LOG_LEVEL=info
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  caddy:
    image: caddy:latest
    container_name: photogrammetry-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.production:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - ../logs:/var/log/caddy
    environment:
      - CADDY_LOG_LEVEL=INFO
    networks:
      - app_network
    depends_on:
      app:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "caddy", "version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  app_network:
    driver: bridge

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
