services:
  app:
    build: ..
    container_name: resilience-api
    restart: unless-stopped
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
    networks:
      - caddy_network

  caddy:
    image: caddy:latest
    container_name: photogrammetry-caddy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile.ip:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_network
    depends_on:
      - app

networks:
  caddy_network:
    driver: bridge

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
